// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.14.0
// source: proto/fibonacci.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFibonacciSliceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X uint64 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y uint64 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *GetFibonacciSliceReq) Reset() {
	*x = GetFibonacciSliceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fibonacci_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFibonacciSliceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFibonacciSliceReq) ProtoMessage() {}

func (x *GetFibonacciSliceReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fibonacci_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFibonacciSliceReq.ProtoReflect.Descriptor instead.
func (*GetFibonacciSliceReq) Descriptor() ([]byte, []int) {
	return file_proto_fibonacci_proto_rawDescGZIP(), []int{0}
}

func (x *GetFibonacciSliceReq) GetX() uint64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *GetFibonacciSliceReq) GetY() uint64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type GetFibonacciSliceRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res []uint64 `protobuf:"varint,1,rep,packed,name=res,proto3" json:"res,omitempty"`
}

func (x *GetFibonacciSliceRes) Reset() {
	*x = GetFibonacciSliceRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fibonacci_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFibonacciSliceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFibonacciSliceRes) ProtoMessage() {}

func (x *GetFibonacciSliceRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fibonacci_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFibonacciSliceRes.ProtoReflect.Descriptor instead.
func (*GetFibonacciSliceRes) Descriptor() ([]byte, []int) {
	return file_proto_fibonacci_proto_rawDescGZIP(), []int{1}
}

func (x *GetFibonacciSliceRes) GetRes() []uint64 {
	if x != nil {
		return x.Res
	}
	return nil
}

var File_proto_fibonacci_proto protoreflect.FileDescriptor

var file_proto_fibonacci_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x69, 0x62, 0x6f, 0x6e, 0x61, 0x63, 0x63,
	0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x46, 0x69, 0x62, 0x6f, 0x6e, 0x61, 0x63, 0x63, 0x69, 0x53, 0x6c,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x01, 0x79, 0x22, 0x28, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x46, 0x69, 0x62, 0x6f, 0x6e, 0x61, 0x63,
	0x63, 0x69, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x03, 0x72, 0x65, 0x73, 0x32, 0x63, 0x0a, 0x10,
	0x46, 0x69, 0x62, 0x6f, 0x6e, 0x61, 0x63, 0x63, 0x69, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x4f, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x46, 0x69, 0x62, 0x6f, 0x6e, 0x61, 0x63, 0x63, 0x69,
	0x53, 0x6c, 0x69, 0x63, 0x65, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65,
	0x74, 0x46, 0x69, 0x62, 0x6f, 0x6e, 0x61, 0x63, 0x63, 0x69, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69,
	0x62, 0x6f, 0x6e, 0x61, 0x63, 0x63, 0x69, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x22,
	0x00, 0x42, 0x08, 0x5a, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_fibonacci_proto_rawDescOnce sync.Once
	file_proto_fibonacci_proto_rawDescData = file_proto_fibonacci_proto_rawDesc
)

func file_proto_fibonacci_proto_rawDescGZIP() []byte {
	file_proto_fibonacci_proto_rawDescOnce.Do(func() {
		file_proto_fibonacci_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_fibonacci_proto_rawDescData)
	})
	return file_proto_fibonacci_proto_rawDescData
}

var file_proto_fibonacci_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_fibonacci_proto_goTypes = []interface{}{
	(*GetFibonacciSliceReq)(nil), // 0: proto.GetFibonacciSliceReq
	(*GetFibonacciSliceRes)(nil), // 1: proto.GetFibonacciSliceRes
}
var file_proto_fibonacci_proto_depIdxs = []int32{
	0, // 0: proto.FibonacciService.GetFibonacciSlice:input_type -> proto.GetFibonacciSliceReq
	1, // 1: proto.FibonacciService.GetFibonacciSlice:output_type -> proto.GetFibonacciSliceRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_fibonacci_proto_init() }
func file_proto_fibonacci_proto_init() {
	if File_proto_fibonacci_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_fibonacci_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFibonacciSliceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_fibonacci_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFibonacciSliceRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_fibonacci_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fibonacci_proto_goTypes,
		DependencyIndexes: file_proto_fibonacci_proto_depIdxs,
		MessageInfos:      file_proto_fibonacci_proto_msgTypes,
	}.Build()
	File_proto_fibonacci_proto = out.File
	file_proto_fibonacci_proto_rawDesc = nil
	file_proto_fibonacci_proto_goTypes = nil
	file_proto_fibonacci_proto_depIdxs = nil
}
